# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 775e0bf83b2dcf1c874ed456a7de59dec7f7a2515d0083540c77d7bdf2572cbdc1dcc7c03e47649366a047a6de2c027e7731716939ecad1b17646f526e3cdf14

test:
  secret_key_base: 3994f5194cd64f5d12ff2cec74b8a9efb4a9ee8c371cfaf433474c4d27e5850baab9ef0d4faac9d3a574dbc910d12a09327e1fb665bbf473c36d8c7adc2df325

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
